name: dart_http_server
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  shelf: ^1.4.0
  hotreloader: ^3.0.5
  shelf_router: ^1.1.3

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.1
